Locale = {
	'Missing document id': 'Hiányzó dokumentumazonosító',
	'Open': 'Megnyit',
	'Recent...': 'Mostanában...',
	'Save As...': 'Mentés mint...',
	'Undo': 'Vissza',
	'Redo': 'Előre',
	'New': 'Új',
	'Yes': 'Igen',
	'Cancel': 'Mégse',
	'There are unsaved changes! Are you sure?': 'Vannak nem elmentett változtatások! Biztos folytatod?',
	'Database error:': 'Adatbázis hiba:',
	'Error fetching file: ': 'Fájl betöltése sikertelen: ',
	'Failed to load ': 'Nem sikerült betölteni ',
	'Could not load template file: ': 'Nem sikerült betölteni a sablon fájlt: ',
	'Error during file open process:': 'Hiba a fájl megnyitása közben: ',
	'Error saving:': 'Hiba mentés közben: ',
	'Exception:': 'Kivétel:',
	'No file chosen': 'Nincs fájl kiválasztva',
	'No matching chunk found for chunk with id: ': 'Nincs egyező chunk azonosító: ',
	'Document Loaded': 'Dokumentum betöltve',
	'Document Saved': 'Dokumentum mentve',
	'Document Removed': 'Dokumentum törölve',
	'Error removing document: ': 'Hiba a dokumentum törlése közben: ',
	'Remove from browser storage': 'Eltávolítás a böngésző tárhelyéről',
	'Remove this document from recent files and browser storage? This cannot be undone.': 'Eltávolítod ezt a dokumentumot a legutóbbi fájlok közül és a böngésző tárhelyéről? Ez nem vonható vissza.',
	'Remove the open document from recent files and browser storage? Any unsaved changes will be lost. This cannot be undone.': 'Eltávolítod a megnyitott dokumentumot a legutóbbi fájlok közül és a böngésző tárhelyéről? A nem mentett változtatások elvesznek. Ez nem vonható vissza.',
	'Export cancelled because another document became active before the save finished.': 'Az export megszakadt, mert a mentés befejezése előtt másik dokumentumra váltottál.',
	'Document changed outside, history action is disabled': 'A dokumentum megváltozott, az előre/hátra lépés le lett tiltva',
	'Document not found: ': 'Dokumentum nem található: ',
	'Could not open the document. The file content is invalid or does not match the selected template.': 'Nem sikerült megnyitni a dokumentumot. A fájl tartalma hibás, vagy nem illik a kiválasztott sablonhoz.',
	'The selected template could not split this file into editable sections. Check that you chose the right template and that the file is not empty or missing required content.': 'A kiválasztott sablon nem tudja szerkeszthető részekre bontani ezt a fájlt. Ellenőrizd, hogy jó sablont választottál-e, és hogy a fájl nem üres vagy hiányos.',
	'Show +1 sentence': '+1 mondat mutatása',
	'Table View': 'Táblázatos nézet',
	'Normal View': 'Normál nézet',
	'': ''
}
